hostname: EXAMPLE-RTR

ip_interfaces:
- interface_id: GigabitEthernet0/0
  ip_address: 198.51.100.34 255.255.255.248
- interface_id: Loopback0
  ip_address: 100.64.5.0 255.255.255.255
- interface_id: GigabitEthernet0/1
  ip_address: 10.20.1.1 255.255.255.0

ip_protocols:
  bgp:
    asn: '65540'
    neighbors:
    - neighbor_as: '65501'
      neighbor_ip: 198.51.100.33
      prefix-lists:
      - list-direction: direction
        list-name: name
    network_statements:
    - mask: 255.255.255.0
      prefix: 100.64.5.0
    - mask: 255.255.255.248
      prefix: 198.51.32.0
  ospf:
    network_statements:
    - area_id: '0'
      prefix: 10.0.1.0 0.0.0.255
    process_id: '100'
  static:
  - mask: 255.255.255.0
    next_hop: null0
    prefix: 100.64.5.0
switching_interfaces:
  access:
  - description: a description
    interface: G0/1
    portfast: enable
    vlan_id: '100'
  trunk:
  - allowed_vlans: 100, 200-300
    interface: G0/1

features:
  ipsec_policy_based:
  - peer: 100.64.1.1
    phase_1:
      authentication: pre-share
      encryption: aes
      group: '2'
      hash: sha
      key_number: '0'
      policy_number: '1'
    phase_2:
      crypto_map:
        map_name: ipsec-crypto-ce1-ce-8
        sequence_number: '10'
      outbound_interface: GigabitEthernet0/0
      protected_networks:
        acl_number: '100'
        dest_mask: 255.255.255.0
        dest_prefix: 10.20.1.0
        dest_wildcard: 0.0.0.255
        source_prefix: 10.30.1.0
        source_wildcard: 0.0.0.255
      transform_set:
        name: ipsec-transform-ce1-ce8
        transforms:
        - esp-aes
        - esp-sha-hmac
    pre_shared_key: ipsec-secret-key-ce1-ce8
    tunnel_number: '1'

  prefix-list:
  - name: my-prefix-inbound
    statements:
    - action: permit
      operator: ge 25
      prefix: 10.0.20.0/24
      sequence: '10'
